version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: switch
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always